# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [2]:
df = pd.read_csv("AviationData.csv", encoding="latin1", low_memory=False)
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [3]:
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [4]:
df.tail()
df.shape
df.isnull().sum()
df.isnull().sum().sort_values(ascending=False)

Schedule                  76307
Air.carrier               72241
FAR.Description           56866
Aircraft.Category         56602
Longitude                 54516
Latitude                  54507
Airport.Code              38757
Airport.Name              36185
Broad.phase.of.flight     27165
Publication.Date          13771
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Fatal.Injuries      11401
Engine.Type                7096
Report.Status              6384
Purpose.of.flight          6192
Number.of.Engines          6084
Total.Uninjured            5912
Weather.Condition          4492
Aircraft.damage            3194
Registration.Number        1382
Injury.Severity            1000
Country                     226
Amateur.Built               102
Model                        92
Make                         63
Location                     52
Accident.Number               0
Investigation.Type            0
Event.Id                      0
Event.Date                    0
dtype: int64

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  str
 1   Investigation.Type      88889 non-null  str
 2   Accident.Number         88889 non-null  str
 3   Event.Date              88889 non-null  str
 4   Location                88837 non-null  str
 5   Country                 88663 non-null  str
 6   Latitude                34382 non-null  str
 7   Longitude               34373 non-null  str
 8   Airport.Code            50132 non-null  str
 9   Airport.Name            52704 non-null  str
 10  Injury.Severity         87889 non-null  str
 11  Aircraft.damage         85695 non-null  str
 12  Aircraft.Category       32287 non-null  str
 13  Registration.Number     87507 non-null  str
 14  Make                    88826 non-null  str
 15  Model                   88797 non-null  str
 16  Amateur.Built           88787 non-null  str
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  str
 19  FAR.Description         32023 non-null  str
 20  Schedule                12582 non-null  str
 21  Purpose.of.flight       82697 non-null  str
 22  Air.carrier             16648 non-null  str
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  str
 28  Broad.phase.of.flight   61724 non-null  str
 29  Report.Status           82505 non-null  str
 30  Publication.Date        75118 non-null  str
dtypes: float64(5), str(26)
memory usage: 21.0 MB

In [6]:
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

In [7]:
df.duplicated().sum()

np.int64(0)

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [8]:
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='str')

In [9]:
relevant_columns = [
    'Event.Date',
    'Investigation.Type',
    'Aircraft.Category',
    'Amateur.Built',
    'Make',
    'Model'
]

df[relevant_columns].head()

,Event.Date,Investigation.Type,Aircraft.Category,Amateur.Built,Make,Model
0,1948-10-24,Accident,NaN,No,Stinson,108-3
1,1962-07-19,Accident,NaN,No,Piper,PA24-180
2,1974-08-30,Accident,NaN,No,Cessna,172M
3,1977-06-19,Accident,NaN,No,Rockwell,112
4,1979-08-02,Accident,NaN,No,Cessna,501

In [10]:
df[relevant_columns].info()

<class 'pandas.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Event.Date          88889 non-null  str
 1   Investigation.Type  88889 non-null  str
 2   Aircraft.Category   32287 non-null  str
 3   Amateur.Built       88787 non-null  str
 4   Make                88826 non-null  str
 5   Model               88797 non-null  str
dtypes: str(6)
memory usage: 4.1 MB

In [11]:
df[relevant_columns].isnull().sum()

Event.Date                0
Investigation.Type        0
Aircraft.Category     56602
Amateur.Built           102
Make                     63
Model                    92
dtype: int64

In [12]:
print("Investigation types:")
print(df['Investigation.Type'].value_counts(dropna=False))

print("\nAircraft categories:")
print(df['Aircraft.Category'].value_counts(dropna=False))

print("\nAmateur-built status:")
print(df['Amateur.Built'].value_counts(dropna=False))

Investigation types:
Investigation.Type
Accident    85015
Incident     3874
Name: count, dtype: int64

Aircraft categories:
Aircraft.Category
NaN                  56602
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

Amateur-built status:
Amateur.Built
No     80312
Yes     8475
NaN      102
Name: count, dtype: int64

In [13]:
print(df['Event.Date'].head())

print("Earliest date:", df['Event.Date'].min())
print("Latest date:", df['Event.Date'].max())

0    1948-10-24
1    1962-07-19
2    1974-08-30
3    1977-06-19
4    1979-08-02
Name: Event.Date, dtype: str
Earliest date: 1948-10-24
Latest date: 2022-12-29

In [14]:
# Convert Event.Date into datetime
df['Event.Date'] = pd.to_datetime(
    df['Event.Date'],
    errors='coerce'
)

# Check date conversion
df['Event.Date'].dtype

dtype('<M8[us]')

In [15]:
# Filter accidents from 1983 onwards
df = df[df['Event.Date'].dt.year >= 1983]

# Keep accident records only
df = df[df['Investigation.Type'] == 'Accident']

# Exclude amateur-built aircraft
df = df[df['Amateur.Built'] == 'No']

# Keep airplanes only
df = df[df['Aircraft.Category'] == 'Airplane']

# Display the filtered dataset
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,1.0,NaN,NaN,IMC,Cruise,Probable Cause,02-05-2011
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,Skydiving,NaN,1.0,NaN,NaN,4.0,VMC,Standing,Probable Cause,17-10-2016
5960,20001214X44100,Accident,DCA83AA036,1983-08-21,"SILVANA, WA",United States,NaN,NaN,S88,NaN,...,Skydiving,NaN,11.0,2.0,NaN,13.0,VMC,Other,Probable Cause,17-10-2016
6669,20001214X44944,Accident,NYC84LA015,1983-10-28,"MIDDLETOWN, PA",United States,NaN,NaN,NaN,NaN,...,Unknown,NaN,1.0,NaN,NaN,29.0,VMC,Climb,Probable Cause,09-12-2011
6806,20001214X45188,Accident,NYC84LA028,1983-11-13,"MARTHA'S VINEYARD, MA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,NaN,NaN,NaN,1.0,VMC,Climb,Probable Cause,05-05-2011

In [16]:
df.shape

(19937, 31)

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [17]:
# Select relevant columns
injury_damage_cols = [
    'Total.Fatal.Injuries',
    'Total.Serious.Injuries',
    'Total.Minor.Injuries',
    'Total.Uninjured',
    'Aircraft.damage'
]

# Display the first five records
df[injury_damage_cols].head()

,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Aircraft.damage
4171,1.0,1.0,NaN,NaN,Destroyed
4285,1.0,NaN,NaN,4.0,NaN
5960,11.0,2.0,NaN,13.0,Destroyed
6669,1.0,NaN,NaN,29.0,NaN
6806,NaN,NaN,NaN,1.0,Substantial

In [18]:
df[injury_damage_cols].info()

<class 'pandas.DataFrame'>
Index: 19937 entries, 4171 to 88886
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Total.Fatal.Injuries    17293 non-null  float64
 1   Total.Serious.Injuries  17215 non-null  float64
 2   Total.Minor.Injuries    17495 non-null  float64
 3   Total.Uninjured         19255 non-null  float64
 4   Aircraft.damage         19503 non-null  str
dtypes: float64(4), str(1)
memory usage: 934.5 KB

In [19]:
df[injury_damage_cols].isnull().sum()

Total.Fatal.Injuries      2644
Total.Serious.Injuries    2722
Total.Minor.Injuries      2442
Total.Uninjured            682
Aircraft.damage            434
dtype: int64

In [20]:
df['Aircraft.damage'].value_counts(dropna=False)

Aircraft.damage
Substantial    16965
Destroyed       2316
NaN              434
Minor            147
Unknown           75
Name: count, dtype: int64

In [21]:
df[[
    'Total.Fatal.Injuries',
    'Total.Serious.Injuries',
    'Total.Minor.Injuries',
    'Total.Uninjured'
]].describe()

,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,17293.00000,17215.000000,17495.000000,19255.000000
mean,0.80096,0.334418,0.248700,5.077642
std,7.03672,2.350883,1.820876,27.731174
min,0.00000,0.000000,0.000000,0.000000
25%,0.00000,0.000000,0.000000,0.000000
50%,0.00000,0.000000,0.000000,1.000000
75%,0.00000,0.000000,0.000000,2.000000
max,295.00000,161.000000,200.000000,576.000000

In [22]:
# Identify injury columns
injury_cols = [
    'Total.Fatal.Injuries',
    'Total.Serious.Injuries',
    'Total.Minor.Injuries',
    'Total.Uninjured'
]

# Convert injury columns to numeric
for col in injury_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Replace negative injury counts with NaN
for col in injury_cols:
    df.loc[df[col] < 0, col] = np.nan

# Check missing values after cleaning
df[injury_cols].isnull().sum()

Total.Fatal.Injuries      2644
Total.Serious.Injuries    2722
Total.Minor.Injuries      2442
Total.Uninjured            682
dtype: int64

In [23]:
# Identify records where all injury counts are available
complete_injury_records = df[injury_cols].notna().all(axis=1)

# Create Total.Occupants
df['Total.Occupants'] = np.nan

df.loc[complete_injury_records, 'Total.Occupants'] = (
    df.loc[complete_injury_records, injury_cols].sum(axis=1)
)

# Display the results
df[[
    'Total.Fatal.Injuries',
    'Total.Serious.Injuries',
    'Total.Minor.Injuries',
    'Total.Uninjured',
    'Total.Occupants'
]].head(10)

,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Total.Occupants
4171,1.0,1.0,NaN,NaN,NaN
4285,1.0,NaN,NaN,4.0,NaN
5960,11.0,2.0,NaN,13.0,NaN
6669,1.0,NaN,NaN,29.0,NaN
6806,NaN,NaN,NaN,1.0,NaN
7084,NaN,NaN,NaN,1.0,NaN
7708,NaN,NaN,NaN,1.0,NaN
8585,NaN,NaN,NaN,4.0,NaN
8591,NaN,NaN,NaN,157.0,NaN
8865,1.0,NaN,NaN,NaN,NaN

In [24]:
# Calculate combined fatal and serious injuries
df['Fatal.Serious.Injuries'] = np.nan

df.loc[complete_injury_records, 'Fatal.Serious.Injuries'] = (
    df.loc[complete_injury_records, 'Total.Fatal.Injuries'] +
    df.loc[complete_injury_records, 'Total.Serious.Injuries']
)

# Calculate fatal/serious injury rate
# Replace zero occupants with NaN to prevent division by zero

df['Fatal.Serious.Injury.Rate'] = (
    df['Fatal.Serious.Injuries'] /
    df['Total.Occupants'].replace(0, np.nan)
)

# Display the new variables
df[[
    'Total.Occupants',
    'Fatal.Serious.Injuries',
    'Fatal.Serious.Injury.Rate'
]].head(10)

      Total.Occupants  Fatal.Serious.Injuries  Fatal.Serious.Injury.Rate
4171              NaN                     NaN                        NaN
4285              NaN                     NaN                        NaN
5960              NaN                     NaN                        NaN
6669              NaN                     NaN                        NaN
6806              NaN                     NaN                        NaN
7084              NaN                     NaN                        NaN
7708              NaN                     NaN                        NaN
8585              NaN                     NaN                        NaN
8591              NaN                     NaN                        NaN
8865              NaN                     NaN                        NaN

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [25]:
# Clean the Aircraft.damage column

# Remove leading/trailing spaces and standardize capitalization
df['Aircraft.damage'] = (
    df['Aircraft.damage']
    .astype('string')
    .str.strip()
    .str.upper()
)

# Standardize unknown values
df['Aircraft.damage'] = df['Aircraft.damage'].replace({
    'UNK': 'UNKNOWN',
    '': pd.NA
})

# Create a binary column to indicate whether the aircraft was destroyed
# 1 = Destroyed
# 0 = Not destroyed (Substantial or Minor damage)
# NaN = Missing or unknown damage information

df['Aircraft.Destroyed'] = df['Aircraft.damage'].map({
    'DESTROYED': 1,
    'SUBSTANTIAL': 0,
    'MINOR': 0
})

# Display the results
df[['Aircraft.damage', 'Aircraft.Destroyed']].head(10)

# Check the distribution of destruction outcomes
print(df['Aircraft.Destroyed'].value_counts(dropna=False))

# Calculate the aircraft destruction rate
destruction_rate = df['Aircraft.Destroyed'].mean() * 100

print(f"Aircraft destruction rate: {destruction_rate:.2f}%")

Aircraft.Destroyed
0.0    17112
1.0     2316
NaN      509
Name: count, dtype: int64
Aircraft destruction rate: 11.92%

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [26]:
# 1. Remove leading and trailing spaces
df['Make'] = (
    df['Make']
    .astype('string')
    .str.strip()
    .str.upper()
    .str.replace(r'\s+', ' ', regex=True)
)

# 2. Replace inconsistent manufacturer names
make_aliases = {
    'AIR TRACTOR INC': 'AIR TRACTOR',
    'CIRRUS DESIGN CORP': 'CIRRUS',
    'CIRRUS DESIGN CORPORATION': 'CIRRUS',
    'DE HAVILLAND': 'DEHAVILLAND',
    'DE HAVILLAND AIRCRAFT': 'DEHAVILLAND',
    'AVIAT AIRCRAFT INC': 'AVIAT'
}

df['Make'] = df['Make'].replace(make_aliases)

# 3. Remove missing, blank and unknown manufacturer names
df = df.dropna(subset=['Make'])

df = df[
    ~df['Make'].isin(['', 'UNKNOWN', 'UNK'])
].copy()

# 4. Count accident records for each manufacturer
make_counts = df['Make'].value_counts()

# 5. Retain manufacturers with at least 50 accident records
eligible_makes = make_counts[make_counts >= 50].index

df = df[df['Make'].isin(eligible_makes)].copy()

# 6. Display the manufacturer counts
print("Number of eligible manufacturers:", df['Make'].nunique())

print("\nAccident records per manufacturer:")
print(df['Make'].value_counts())

# 7. Check the cleaned Make column
print("\nFirst 10 manufacturer names:")
print(df['Make'].head(10))

# 8. Check for missing values
print("\nMissing manufacturer names:", df['Make'].isna().sum())

Number of eligible manufacturers: 30

Accident records per manufacturer:
Make
CESSNA                            7029
PIPER                             3938
BEECH                             1392
BOEING                             553
AIR TRACTOR                        423
MOONEY                             358
CIRRUS                             349
BELLANCA                           217
MAULE                              215
AERONCA                            200
DEHAVILLAND                        160
CHAMPION                           157
GRUMMAN                            146
AVIAT                              145
LUSCOMBE                           141
STINSON                            129
NORTH AMERICAN                     104
EMBRAER                             98
TAYLORCRAFT                         93
AERO COMMANDER                      90
AIRBUS                              82
SOCATA                              74
DIAMOND AIRCRAFT IND INC            72
MCDONNELL DOUGLAS                   66
GRUMMAN ACFT ENG COR-SCHWEIZER      58
ROCKWELL INTERNATIONAL              57
RAYTHEON AIRCRAFT COMPANY           56
AYRES                               55
ERCOUPE                             52
AMERICAN CHAMPION AIRCRAFT          51
Name: count, dtype: Int64

First 10 manufacturer names:
4171           PIPER
4285     DEHAVILLAND
6806           BEECH
7084          CESSNA
7708           BEECH
8585           PIPER
8865           PIPER
10247         CESSNA
10605         CESSNA
10688         CESSNA
Name: Make, dtype: string

Missing manufacturer names: 0

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [27]:
# 1. Remove missing model names
df = df.dropna(subset=['Model']).copy()

# 2. Remove leading/trailing spaces and standardize capitalization
df['Model'] = (
    df['Model']
    .astype('string')
    .str.strip()
    .str.upper()
    .str.replace(r'\s+', ' ', regex=True)
)

# 3. Remove blank and unknown model names
df = df[
    ~df['Model'].isin(['', 'UNKNOWN', 'UNK'])
].copy()

# 4. Inspect the most common aircraft models
print("Top 20 Aircraft Models:")
print(df['Model'].value_counts().head(20))

# 5. Count accident records for each Make and Model
make_model_counts = (
    df.groupby(['Make', 'Model'])
    .size()
    .reset_index(name='Accident_Count')
    .sort_values(by='Accident_Count', ascending=False)
)

print("\nAccident counts for each Make and Model:")
print(make_model_counts.head(20))

# 6. Check whether model names are unique to each manufacturer
model_make_counts = df.groupby('Model')['Make'].nunique()

shared_models = model_make_counts[model_make_counts > 1]

print("\nNumber of model labels associated with multiple manufacturers:")
print(len(shared_models))

print("\nExamples of model labels shared by different manufacturers:")
print(shared_models.head(20))

# 7. Create a unique aircraft identifier using Make and Model
df['Make_Model'] = df['Make'] + ' | ' + df['Model']

# 8. Inspect the new unique identifier
print("\nUnique aircraft identifiers:")
print(df['Make_Model'].value_counts().head(20))

# 9. Check the final results
print("\nTotal unique aircraft types:", df['Make_Model'].nunique())
print("Missing model names:", df['Model'].isna().sum())

# Display final dataframe
df[['Make', 'Model', 'Make_Model']].head(10)

Top 20 Aircraft Models:
Model
172          763
152          311
182          300
172S         272
PA28         268
172N         249
SR22         232
180          212
A36          181
172M         179
150          177
PA-18-150    175
PA-28-140    169
172P         141
737          118
140          117
172R         108
170B         107
PA-28-180    105
PA-28-161    101
Name: count, dtype: Int64

Accident counts for each Make and Model:
        Make      Model  Accident_Count
667   CESSNA        172             763
657   CESSNA        152             311
730   CESSNA        182             300
703   CESSNA       172S             272
1733   PIPER       PA28             268
698   CESSNA       172N             249
1063  CIRRUS       SR22             232
715   CESSNA        180             212
697   CESSNA       172M             179
642   CESSNA        150             177
1581   PIPER  PA-18-150             175
1622   PIPER  PA-28-140             169
288    BEECH        A36             164
699   CESSNA       172P             141
479   BOEING        737             118
640   CESSNA        140             116
701   CESSNA       172R             108
666   CESSNA       170B             107
1628   PIPER  PA-28-180             105
1627   PIPER  PA-28-161             101

Number of model labels associated with multiple manufacturers:
50

Examples of model labels shared by different manufacturers:
Model
100      2
112      2
112A     2
140      2
1900D    2
200      2
320      2
350      2
390      2
400      2
400A     2
401B     2
402A     2
402B     2
500      2
500 S    2
560      2
58       2
690A     2
7AC      3
Name: Make, dtype: int64

Unique aircraft identifiers:
Make_Model
CESSNA | 172         763
CESSNA | 152         311
CESSNA | 182         300
CESSNA | 172S        272
PIPER | PA28         268
CESSNA | 172N        249
CIRRUS | SR22        232
CESSNA | 180         212
CESSNA | 172M        179
CESSNA | 150         177
PIPER | PA-18-150    175
PIPER | PA-28-140    169
BEECH | A36          164
CESSNA | 172P        141
BOEING | 737         118
CESSNA | 140         116
CESSNA | 172R        108
CESSNA | 170B        107
PIPER | PA-28-180    105
PIPER | PA-28-161    101
Name: count, dtype: Int64

Total unique aircraft types: 1900
Missing model names: 0

              Make      Model           Make_Model
4171         PIPER  PA-28-140    PIPER | PA-28-140
4285   DEHAVILLAND      DHC-6  DEHAVILLAND | DHC-6
6806         BEECH        C35          BEECH | C35
7084        CESSNA       180K        CESSNA | 180K
7708         BEECH         99           BEECH | 99
8585         PIPER  PA-23-250    PIPER | PA-23-250
8865         PIPER  PA-18-150    PIPER | PA-18-150
10247       CESSNA      R172E       CESSNA | R172E
10605       CESSNA       182A        CESSNA | 182A
10688       CESSNA       182Q        CESSNA | 182Q

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [28]:

# 1. INSPECT ORIGINAL VALUES


columns_to_clean = [
    'Engine.Type',
    'Weather.Condition',
    'Number.of.Engines',
    'Purpose.of.flight',
    'Broad.phase.of.flight'
]

# Display data types and missing values
print("DATA TYPES:")
print(df[columns_to_clean].dtypes)

print("\nMISSING VALUES:")
print(df[columns_to_clean].isnull().sum())

# Inspect unique values in each column
for col in columns_to_clean:
    print(f"\nUnique values in {col}:")
    print(df[col].value_counts(dropna=False))


# Remove extra spaces and standardize capitalization
df['Engine.Type'] = (
    df['Engine.Type']
    .astype('string')
    .str.strip()
    .str.upper()
)

# Standardize unknown values
df['Engine.Type'] = df['Engine.Type'].replace({
    'UNK': 'UNKNOWN',
    'NONE': 'UNKNOWN',
    '': pd.NA
})


# Remove extra spaces and standardize capitalization
df['Weather.Condition'] = (
    df['Weather.Condition']
    .astype('string')
    .str.strip()
    .str.upper()
)

# Standardize unknown values
df['Weather.Condition'] = df['Weather.Condition'].replace({
    'UNK': 'UNKNOWN',
    '': pd.NA
})

# Convert number of engines to numeric
df['Number.of.Engines'] = pd.to_numeric(
    df['Number.of.Engines'],
    errors='coerce'
)

# Replace zero or negative engine counts with NaN
# Conventional airplanes must have at least one engine
df.loc[
    df['Number.of.Engines'] <= 0,
    'Number.of.Engines'
] = np.nan


# Remove extra spaces and standardize capitalization
df['Purpose.of.flight'] = (
    df['Purpose.of.flight']
    .astype('string')
    .str.strip()
    .str.upper()
)

# Standardize unknown and blank values
df['Purpose.of.flight'] = df['Purpose.of.flight'].replace({
    'UNK': 'UNKNOWN',
    '': pd.NA
})

# Remove extra spaces and standardize capitalization
df['Broad.phase.of.flight'] = (
    df['Broad.phase.of.flight']
    .astype('string')
    .str.strip()
    .str.upper()
)

# Standardize unknown and blank values
df['Broad.phase.of.flight'] = df['Broad.phase.of.flight'].replace({
    'UNK': 'UNKNOWN',
    '': pd.NA
})


# Display cleaned unique values and counts
for col in columns_to_clean:
    print(f"\nCleaned values for {col}:")
    print(df[col].value_counts(dropna=False))

# Check missing values after cleaning
print("\nMISSING VALUES AFTER CLEANING:")
print(df[columns_to_clean].isnull().sum())

# Display the cleaned columns
df[columns_to_clean].head(10)

DATA TYPES:
Engine.Type                  str
Weather.Condition            str
Number.of.Engines        float64
Purpose.of.flight            str
Broad.phase.of.flight        str
dtype: object

MISSING VALUES:
Engine.Type               2444
Weather.Condition         1507
Number.of.Engines         1426
Purpose.of.flight         1909
Broad.phase.of.flight    14130
dtype: int64

Unique values in Engine.Type:
Engine.Type
Reciprocating    12743
NaN               2444
Turbo Prop         877
Turbo Fan          364
Unknown             67
Turbo Jet           45
Turbo Shaft          8
UNK                  1
Name: count, dtype: int64

Unique values in Weather.Condition:
Weather.Condition
VMC    13979
NaN     1507
IMC      873
Unk      147
UNK       43
Name: count, dtype: int64

Unique values in Number.of.Engines:
Number.of.Engines
1.0    13138
2.0     1938
NaN     1426
4.0       28
3.0       15
0.0        4
Name: count, dtype: int64

Unique values in Purpose.of.flight:
Purpose.of.flight
Personal                     9781
Instructional                2387
NaN                          1909
Aerial Application            721
Business                      394
Unknown                       254
Positioning                   253
Skydiving                     156
Aerial Observation            146
Other Work Use                118
Banner Tow                     86
Ferry                          70
Flight Test                    68
Executive/corporate            59
Glider Tow                     29
Public Aircraft - Federal      27
Public Aircraft                26
Public Aircraft - State        20
Air Race show                  14
Firefighting                   12
Public Aircraft - Local        10
PUBS                            3
Air Race/show                   2
Air Drop                        2
ASHO                            2
Name: count, dtype: int64

Unique values in Broad.phase.of.flight:
Broad.phase.of.flight
NaN            14130
Landing         1105
Takeoff          421
Cruise           233
Approach         209
Maneuvering      126
Taxi              92
Go-around         81
Descent           59
Climb             48
Standing          33
Unknown           10
Other              2
Name: count, dtype: int64

Cleaned values for Engine.Type:
Engine.Type
RECIPROCATING    12743
<NA>              2444
TURBO PROP         877
TURBO FAN          364
UNKNOWN             68
TURBO JET           45
TURBO SHAFT          8
Name: count, dtype: Int64

Cleaned values for Weather.Condition:
Weather.Condition
VMC        13979
<NA>        1507
IMC          873
UNKNOWN      190
Name: count, dtype: Int64

Cleaned values for Number.of.Engines:
Number.of.Engines
1.0    13138
2.0     1938
NaN     1430
4.0       28
3.0       15
Name: count, dtype: int64

Cleaned values for Purpose.of.flight:
Purpose.of.flight
PERSONAL                     9781
INSTRUCTIONAL                2387
<NA>                         1909
AERIAL APPLICATION            721
BUSINESS                      394
UNKNOWN                       254
POSITIONING                   253
SKYDIVING                     156
AERIAL OBSERVATION            146
OTHER WORK USE                118
BANNER TOW                     86
FERRY                          70
FLIGHT TEST                    68
EXECUTIVE/CORPORATE            59
GLIDER TOW                     29
PUBLIC AIRCRAFT - FEDERAL      27
PUBLIC AIRCRAFT                26
PUBLIC AIRCRAFT - STATE        20
AIR RACE SHOW                  14
FIREFIGHTING                   12
PUBLIC AIRCRAFT - LOCAL        10
PUBS                            3
AIR RACE/SHOW                   2
AIR DROP                        2
ASHO                            2
Name: count, dtype: Int64

Cleaned values for Broad.phase.of.flight:
Broad.phase.of.flight
<NA>           14130
LANDING         1105
TAKEOFF          421
CRUISE           233
APPROACH         209
MANEUVERING      126
TAXI              92
GO-AROUND         81
DESCENT           59
CLIMB             48
STANDING          33
UNKNOWN           10
OTHER              2
Name: count, dtype: Int64

MISSING VALUES AFTER CLEANING:
Engine.Type               2444
Weather.Condition         1507
Number.of.Engines         1430
Purpose.of.flight         1909
Broad.phase.of.flight    14130
dtype: int64

,Engine.Type,Weather.Condition,Number.of.Engines,Purpose.of.flight,Broad.phase.of.flight
4171,RECIPROCATING,IMC,1.0,PERSONAL,CRUISE
4285,TURBO PROP,VMC,2.0,SKYDIVING,STANDING
6806,RECIPROCATING,VMC,1.0,PERSONAL,CLIMB
7084,RECIPROCATING,VMC,1.0,PERSONAL,TAKEOFF
7708,TURBO PROP,VMC,2.0,UNKNOWN,LANDING
8585,RECIPROCATING,VMC,2.0,PERSONAL,APPROACH
8865,RECIPROCATING,VMC,1.0,AERIAL APPLICATION,MANEUVERING
10247,RECIPROCATING,VMC,1.0,PERSONAL,APPROACH
10605,RECIPROCATING,VMC,1.0,SKYDIVING,MANEUVERING
10688,RECIPROCATING,VMC,1.0,PERSONAL,MANEUVERING

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [29]:
# Inspect missing values in each column
missing_summary = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Missing Percentage': (df.isnull().mean() * 100).round(2)
})

print("Missing values before column removal:")
display(missing_summary.sort_values(
    by='Missing Percentage', ascending=False
))

# Identify columns with more than 50% missing values
columns_to_drop = missing_summary[
    missing_summary['Missing Percentage'] > 50
].index

print("\nColumns to be removed:")
print(columns_to_drop.tolist())

# Drop columns with more than 50% missing values
df.drop(columns=columns_to_drop, inplace=True)

# Inspect the dataframe after removal
print("\nDataframe shape after column removal:", df.shape)
display(df.head())

Missing values before column removal:

                           Missing Values  Missing Percentage
Schedule                            15176               91.70
Broad.phase.of.flight               14130               85.38
Air.carrier                          8988               54.31
Airport.Code                         5427               32.79
Airport.Name                         5356               32.36
Report.Status                        2932               17.72
Fatal.Serious.Injury.Rate            2732               16.51
Total.Occupants                      2544               15.37
Fatal.Serious.Injuries               2544               15.37
Engine.Type                          2444               14.77
Total.Serious.Injuries               2382               14.39
Total.Fatal.Injuries                 2310               13.96
Total.Minor.Injuries                 2148               12.98
Purpose.of.flight                    1909               11.54
Weather.Condition                    1507                9.11
Number.of.Engines                    1430                8.64
Longitude                            1082                6.54
Latitude                             1079                6.52
Publication.Date                      591                3.57
Total.Uninjured                       565                3.41
Aircraft.Destroyed                    429                2.59
Aircraft.damage                       365                2.21
Injury.Severity                       184                1.11
FAR.Description                       181                1.09
Registration.Number                   123                0.74
Location                                3                0.02
Country                                 1                0.01
Event.Id                                0                0.00
Event.Date                              0                0.00
Accident.Number                         0                0.00
Investigation.Type                      0                0.00
Model                                   0                0.00
Amateur.Built                           0                0.00
Aircraft.Category                       0                0.00
Make                                    0                0.00
Make_Model                              0                0.00

Columns to be removed:
['Schedule', 'Air.carrier', 'Broad.phase.of.flight']

Dataframe shape after column removal: (16549, 33)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Report.Status,Publication.Date,Total.Occupants,Fatal.Serious.Injuries,Fatal.Serious.Injury.Rate,Aircraft.Destroyed,Make_Model
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,IMC,Probable Cause,02-05-2011,NaN,NaN,NaN,1.0,PIPER | PA-28-140
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,NaN,4.0,VMC,Probable Cause,17-10-2016,NaN,NaN,NaN,NaN,DEHAVILLAND | DHC-6
6806,20001214X45188,Accident,NYC84LA028,1983-11-13,"MARTHA'S VINEYARD, MA",United States,NaN,NaN,NaN,NaN,...,NaN,1.0,VMC,Probable Cause,05-05-2011,NaN,NaN,NaN,0.0,BEECH | C35
7084,20001214X45339,Accident,LAX84LA110,1983-12-22,"SANTA ROSA ISLAND, CA",United States,NaN,NaN,NaN,PRIVATE,...,NaN,1.0,VMC,Probable Cause,01-02-2016,NaN,NaN,NaN,0.0,CESSNA | 180K
7708,20001214X38957,Accident,ATL84LA120,1984-03-14,"MYRTLE BEACH, SC",United States,NaN,NaN,CRE,GRAND STRAND,...,NaN,1.0,VMC,Probable Cause,24-09-2018,NaN,NaN,NaN,0.0,BEECH | 99

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [30]:
# Save the cleaned DataFrame to a CSV file
df.to_csv('AviationData_Cleaned.csv', index=False)

print("Cleaned DataFrame successfully saved as AviationData_Cleaned.csv")

Cleaned DataFrame successfully saved as AviationData_Cleaned.csv